"""empty message

Revision ID: 2ffe83ee752a
Revises: 
Create Date: 2021-09-01 21:17:40.384716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffe83ee752a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('totalhist',
    sa.Column('time_stamp', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('time_stamp')
    )
    op.drop_column('holding', 'day_change')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holding', sa.Column('day_change', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_table('totalhist')
    # ### end Alembic commands ###
